basePath: /
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:3001
info:
  contact:
    email: support@swagger.io
    name: vinod
    url: http://www.swagger.io/support
  description: This is a sample gin web server
  title: Swagger Example API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Hello
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: hellow example
      tags:
      - example
swagger: "2.0"
